import './globals.css'
import { Poppins } from 'next/font/google'
import Header from './component/Header'
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from './component/Footer';

const inter = Poppins({
  weight: ['100','200','300','400','500','600','700','800','900'],
  subsets: ['latin'],
})
 


export const metadata = {
  title: 'Saiyathra',
  description: 'Generated by webdads2u',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer/>
        </body>
    </html>
  )
}
